export const SAVE_DATA = 'SAVE_DATA';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAIL = 'SAVE_DATA_FAIL';

export const SEARCH_DATA = 'SEARCH_DATA';
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const SEARCH_DATA_FAIL = 'SEARCH_DATA_FAIL';

export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
